language: ruby
rvm:
  - 2.1

before_install:
  - export TZ=Europe/London
  - openssl aes-256-cbc -K $encrypted_a1acb7ef69a3_key -iv $encrypted_a1acb7ef69a3_iv -in deploy_key.enc -out deploy_key -d

install: gem install jekyll html-proofer

script: jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 deploy_key # this key should have push access
  - ssh-add deploy_key
  - git remote add deploy git@github.com:kausar007/kausarbangash.com-deploy.git
  - git push deploy master
